postgres_local:
  application_name: "Rentateam"
  host: "localhost"
  port: "5436"
  user: "postgres"
  password: "postgres"
  database: "postgres"
  ssl_mode: "disable"


server_http:
  name: "Rentateam"
  host: "localhost"
  port: "8080"